name: UPDATE TO LATEST

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20,8,14 * * *"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - REPO: Wox-launcher/Wox
            TYPE: bin
            DIRECTORY: wox-bin
            ASSET: wox-linux-amd64
          - REPO: hiddify/hiddify-next
            TYPE: bin
            DIRECTORY: hiddify.next-bin
            ASSET: hiddify-linux-x64.zip
          - REPO: LorenEteval/Furious
            TYPE: source
            DIRECTORY: furious
            ASSET: No
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: pozetroninc/github-action-get-latest-release@master
        id: get_release
        with:
          repository: ${{ matrix.REPO }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          pacman -Syu --noconfirm
          pacman -S python python-pip git openssh openssl openssl-1.1 --noconfirm
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install requests
          python $PY
          rm -rf .venv
        env:
          PKGBUILD: ${{ matrix.DIRECTORY }}/PKGBUILD
          PY: py/${{ matrix.TYPE }}.py
          REPO: ${{ matrix.REPO }}
          LATEST: ${{ steps.get_release.outputs.id }}
          ASSET: ${{ matrix.ASSET }}

      - env:
          DIRECTORY: ${{ matrix.DIRECTORY }}
        run: |
          useradd builder -m
          chmod -R a+rw .
          cd $DIRECTORY
          sudo -u builder makepkg --printsrcinfo > .SRCINFO
          rm -rf file
          cd ..
      - name: push
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          keep_history: true
          allow_empty_commit: false
          commit_message: update version
          target_branch: bot-${{ matrix.DIRECTORY }}
          build_dir: .
          committer: ${{ secrets.COMMITTER }}
          author: ${{ secrets.AUTHOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push:
    needs: check
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - REPO: Wox-launcher/Wox
            DIRECTORY: wox-bin
          - REPO: hiddify/hiddify-next
            DIRECTORY: hiddify.next-bin
          - REPO: LorenEteval/Furious
            DIRECTORY: furious
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: bot-${{ matrix.DIRECTORY }}
      - run: |
          version=$(<"$FILE")
          if [[ "$version" == *"new"* ]]; then
            echo "Version New. Exiting workflow."
            exit 1
          else
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "Version not New. Continuing workflow."
          fi
        env:
          FILE: ${{ matrix.DIRECTORY }}/version.txt
        id: version
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.aur }}
          log-public-key: false
      - name: push
        env:
          result: ${{ steps.version.outputs.version }}
          name: ${{ secrets.name }}
          email: ${{ secrets.email }}
          DIRECTORY: ${{ matrix.DIRECTORY }}
        run: |
          mkdir new
          cd new
          ssh-keyscan -t rsa aur.archlinux.org >> ~/.ssh/known_hosts
          git clone ssh://aur@aur.archlinux.org/$DIRECTORY.git .
          git config --local user.email $email
          git config --local user.name $name
          cp ../$DIRECTORY/PKGBUILD ./
          cp ../$DIRECTORY/.SRCINFO ./
          git add PKGBUILD
          git add .SRCINFO
          git commit -m  "update version to $result"
          git push
          git clone git@github.com:aucub/aur.git
          cp PKGBUILD aur/$DIRECTORY/
          cp .SRCINFO aur/$DIRECTORY/
          cd aur
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --local user.email $email
          git config --local user.name $name
          git add $DIRECTORY/PKGBUILD
          git add $DIRECTORY/.SRCINFO
          git commit -m  "update $DIRECTORY version to $result"
          git push
